modLoader="javafml" #mandatory

loaderVersion="[33,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="GNU General Public License v3.0"

issueTrackerURL="https://github.com/congueror/CLib/issues" #optional

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory

modId="clib" #mandatory

version="1.2.0" #mandatory

displayName="Conguerors Library" #mandatory

# A URL to query for updates for this mod. See the JSON update specification <here>
updateJSONURL="https://raw.githubusercontent.com/congueror/CLib/master/update.json" #optional

# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://www.curseforge.com/minecraft/mc-mods/clib" #optional

# A file name (in the root of the mod JAR) containing a logo for display
logoFile="logo.png" #optional

# A text field displayed in the mod UI
credits="Congueror(me), paint.net(for texture making), The nice people of MMD Discord Server https://discord.mcmoddev.com/ and of Forge Discord Server  https://discord.gg/UvedJ9m, TurtyWurty for the tutorials https://discord.gg/d5cGhKQ" #optional

# A text field displayed in the mod UI
authors="Congueror" #optional

# The description text for the mod (multi line!) (#mandatory)
description='''
Adds a bunch o' ores
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.clib]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[33,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
[[dependencies.clib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2]"
    ordering="NONE"
    side="BOTH"
